spring.application.name=Menu-service

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/menu_service?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#JWT
jwt.secret=6Kd#9pL$2xR7@aZhG5fT!jE8mVbQs3wY
jwt.expiration=86400

#server
server.port=8082

#logging
logging.level.org.springframework.security=DEBUG
logging.level.com.restaurant=DEBUG